// Copyright (C) 2026 The OpenEverest Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package preflight

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/client/fake"

	common "github.com/openeverest/openeverest/v2/api/common/v1alpha1"
	"github.com/openeverest/openeverest/v2/api/core/v1alpha1"
	"github.com/openeverest/openeverest/v2/provider-runtime/controller"
)

// targetSpecYAML mirrors the chart's generated provider-spec.yaml: a bare
// `spec:` document. Release 0.3 removes mongod 6.0.19-16.
const targetSpecYAML = `# generated by provider-sdk
spec:
  release:
    version: "0.3"
    minUpgradableFrom: "0.2"
  components:
    engine:
      type: mongod
  componentTypes:
    mongod:
      defaultVersion: "8.0.12-4"
      versions:
        - version: "6.0.19-16"
          deprecated: true
          removedInVersion: "0.3"
        - version: "8.0.12-4"
  defaultVersion: "8.0.12"
  versions:
    - name: "8.0.12"
      components:
        engine: "8.0.12-4"
`

type stubProvider struct {
	controller.BaseProvider
}

func (p *stubProvider) Validate(*controller.Context) error { return nil }
func (p *stubProvider) Sync(*controller.Context) error     { return nil }
func (p *stubProvider) Status(*controller.Context) (controller.Status, error) {
	return controller.Status{}, nil
}
func (p *stubProvider) Cleanup(*controller.Context) error { return nil }

func newStubProvider() *stubProvider {
	return &stubProvider{BaseProvider: controller.BaseProvider{ProviderName: "psmdb"}}
}

func writeTargetSpec(t *testing.T, content string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "provider-spec.yaml")
	require.NoError(t, os.WriteFile(path, []byte(content), 0o600))
	return path
}

//nolint:ireturn // client.Client is the controller-runtime client abstraction
func newFakeClient(t *testing.T, objs ...client.Object) client.Client {
	t.Helper()
	scheme := runtime.NewScheme()
	require.NoError(t, v1alpha1.AddToScheme(scheme))
	return fake.NewClientBuilder().WithScheme(scheme).WithObjects(objs...).Build()
}

func installedProvider(release string) *v1alpha1.Provider {
	p := &v1alpha1.Provider{ObjectMeta: metav1.ObjectMeta{Name: "psmdb"}}
	if release != "" {
		p.Spec.Release = &v1alpha1.Release{Version: release}
	}
	return p
}

func mongoInstance(name, engineVersion string) *v1alpha1.Instance {
	return &v1alpha1.Instance{
		ObjectMeta: metav1.ObjectMeta{Name: name, Namespace: "db"},
		Spec: v1alpha1.InstanceSpec{
			ProviderRef: common.ObjectRef{Name: "psmdb"},
			Components: map[string]v1alpha1.ComponentSpec{
				"engine": {Version: engineVersion},
			},
		},
	}
}

func TestRun_Blocked(t *testing.T) {
	t.Parallel()

	cl := newFakeClient(t,
		installedProvider("0.2"),
		mongoInstance("mongo-legacy", "6.0.19-16"),
		mongoInstance("mongo-prod", "8.0.12-4"),
	)
	var out bytes.Buffer

	err := Run(t.Context(), newStubProvider(), Options{
		TargetSpecFile: writeTargetSpec(t, targetSpecYAML),
		Out:            &out,
		Client:         cl,
	})

	require.ErrorIs(t, err, ErrUpgradeBlocked)
	report := out.String()
	assert.Contains(t, report, "Provider psmdb: 0.2 → 0.3")
	assert.Contains(t, report, "Checked 2 instance(s).")
	assert.Contains(t, report, "mongo-legacy")
	assert.Contains(t, report, "removed in provider 0.3")
	assert.NotContains(t, report, "mongo-prod")
	assert.Contains(t, report, "Result: BLOCKED (1 error(s), 0 warning(s)). No changes applied.")
}

func TestRun_Passes(t *testing.T) {
	t.Parallel()

	cl := newFakeClient(t,
		installedProvider("0.2"),
		mongoInstance("mongo-prod", "8.0.12-4"),
	)
	var out bytes.Buffer

	err := Run(t.Context(), newStubProvider(), Options{
		TargetSpecFile: writeTargetSpec(t, targetSpecYAML),
		Out:            &out,
		Client:         cl,
	})

	require.NoError(t, err)
	assert.Contains(t, out.String(), "Result: OK (0 warning(s)). Upgrade may proceed.")
}

func TestRun_NoInstalledProviderWarnsButProceeds(t *testing.T) {
	t.Parallel()

	cl := newFakeClient(t, mongoInstance("mongo-prod", "8.0.12-4"))
	var out bytes.Buffer

	err := Run(t.Context(), newStubProvider(), Options{
		TargetSpecFile: writeTargetSpec(t, targetSpecYAML),
		Out:            &out,
		Client:         cl,
	})

	require.NoError(t, err)
	report := out.String()
	assert.Contains(t, report, "Provider psmdb: unknown → 0.3")
	assert.Contains(t, report, "cannot verify the upgrade path")
	assert.Contains(t, report, "Result: OK (1 warning(s)). Upgrade may proceed.")
}

func TestRun_FloorBlocksOldRelease(t *testing.T) {
	t.Parallel()

	cl := newFakeClient(t, installedProvider("0.1"))
	var out bytes.Buffer

	err := Run(t.Context(), newStubProvider(), Options{
		TargetSpecFile: writeTargetSpec(t, targetSpecYAML),
		Out:            &out,
		Client:         cl,
	})

	require.ErrorIs(t, err, ErrUpgradeBlocked)
	assert.Contains(t, out.String(), "requires at least 0.2")
}

func TestRun_IgnoresInstancesOfOtherProviders(t *testing.T) {
	t.Parallel()

	other := mongoInstance("pg-1", "6.0.19-16")
	other.Spec.ProviderRef.Name = "postgresql"
	cl := newFakeClient(t, installedProvider("0.2"), other)
	var out bytes.Buffer

	err := Run(t.Context(), newStubProvider(), Options{
		TargetSpecFile: writeTargetSpec(t, targetSpecYAML),
		Out:            &out,
		Client:         cl,
	})

	require.NoError(t, err)
	assert.Contains(t, out.String(), "Checked 0 instance(s).")
}

func TestLoadTargetSpec(t *testing.T) {
	t.Parallel()

	t.Run("bare spec document", func(t *testing.T) {
		t.Parallel()

		spec, err := loadTargetSpec(writeTargetSpec(t, targetSpecYAML))

		require.NoError(t, err)
		require.NotNil(t, spec.Release)
		assert.Equal(t, "0.3", spec.Release.Version)
		assert.Equal(t, "0.2", spec.Release.MinUpgradableFrom)
	})

	t.Run("full provider manifest", func(t *testing.T) {
		t.Parallel()

		manifest := "apiVersion: core.openeverest.io/v1alpha1\nkind: Provider\nmetadata:\n  name: psmdb\n" + targetSpecYAML

		spec, err := loadTargetSpec(writeTargetSpec(t, manifest))

		require.NoError(t, err)
		require.NotNil(t, spec.Release)
		assert.Equal(t, "0.3", spec.Release.Version)
	})

	t.Run("missing file", func(t *testing.T) {
		t.Parallel()

		_, err := loadTargetSpec(filepath.Join(t.TempDir(), "nope.yaml"))

		require.Error(t, err)
	})

	t.Run("empty path", func(t *testing.T) {
		t.Parallel()

		_, err := loadTargetSpec("")

		require.Error(t, err)
	})
}
