// Code generated by gen-rbac-resources. DO NOT EDIT.

package rbac

// AllResources is a list of all resource names extracted from the API specification.
var AllResources = []string{
	"backup-classes",
	"backup-imports",
	"backup-storages",
	"backups",
	"clusters",
	"config-maps",
	"instance-presets",
	"instances",
	"monitoring-configs",
	"namespaces",
	"plugins",
	"providers",
	"restores",
	"secrets",
}

// resourcePathMap maps API paths to their resource names.
// Paths use colon notation for parameters (e.g., "/:namespace/clusters").
var resourcePathMap = map[string]string{
	"/clusters":                                                               "clusters",
	"/clusters/:cluster/backup-classes":                                       "backup-classes",
	"/clusters/:cluster/backup-classes/:backupClass":                          "backup-classes",
	"/clusters/:cluster/instance-presets":                                     "instance-presets",
	"/clusters/:cluster/instance-presets/:name":                               "instance-presets",
	"/clusters/:cluster/instance-presets/:name/resolve":                       "instance-presets",
	"/clusters/:cluster/namespaces":                                           "namespaces",
	"/clusters/:cluster/namespaces/:namespace/backup-imports":                 "backup-imports",
	"/clusters/:cluster/namespaces/:namespace/backup-imports/:name":           "backup-imports",
	"/clusters/:cluster/namespaces/:namespace/backup-storages":                "backup-storages",
	"/clusters/:cluster/namespaces/:namespace/backup-storages/:name":          "backup-storages",
	"/clusters/:cluster/namespaces/:namespace/backups":                        "backups",
	"/clusters/:cluster/namespaces/:namespace/backups/:backup":                "backups",
	"/clusters/:cluster/namespaces/:namespace/config-maps":                    "config-maps",
	"/clusters/:cluster/namespaces/:namespace/config-maps/:name":              "config-maps",
	"/clusters/:cluster/namespaces/:namespace/instances":                      "instances",
	"/clusters/:cluster/namespaces/:namespace/instances/:instance":            "instances",
	"/clusters/:cluster/namespaces/:namespace/instances/:instance/backups":    "backups",
	"/clusters/:cluster/namespaces/:namespace/instances/:instance/connection": "instances",
	"/clusters/:cluster/namespaces/:namespace/instances/:instance/restores":   "restores",
	"/clusters/:cluster/namespaces/:namespace/monitoring-configs":             "monitoring-configs",
	"/clusters/:cluster/namespaces/:namespace/monitoring-configs/:name":       "monitoring-configs",
	"/clusters/:cluster/namespaces/:namespace/restores":                       "restores",
	"/clusters/:cluster/namespaces/:namespace/restores/:restore":              "restores",
	"/clusters/:cluster/namespaces/:namespace/secrets":                        "secrets",
	"/clusters/:cluster/namespaces/:namespace/secrets/:name":                  "secrets",
	"/clusters/:cluster/plugin-context":                                       "plugins",
	"/clusters/:cluster/plugins":                                              "plugins",
	"/clusters/:cluster/providers":                                            "providers",
	"/clusters/:cluster/providers/:provider":                                  "providers",
	"/clusters/:name":                                                         "clusters",
}

// skipPaths lists API paths that should skip RBAC checks.
var skipPaths = []string{
	"/auth/revoke",
	"/auth/token",
	"/cluster-info",
	"/permissions",
	"/resources",
	"/settings",
	"/version",
}

// GetResourcePathMap returns a copy of the resource path map with an optional base path prefix.
func GetResourcePathMap(basePath string) map[string]string {
	result := make(map[string]string, len(resourcePathMap))
	for path, resource := range resourcePathMap {
		result[basePath+path] = resource
	}
	return result
}

// GetSkipPaths returns a copy of the skip paths with an optional base path prefix.
func GetSkipPaths(basePath string) []string {
	result := make([]string, len(skipPaths))
	for i, path := range skipPaths {
		result[i] = basePath + path
	}
	return result
}
